name: style
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - uses: actions/checkout@v1
    - name: deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install wget pycodestyle
    - name: style
      shell: bash
      run: |
        git clone https://github.com/osrf/rmf_schedule_visualizer
        source /opt/ros/eloquent/setup.bash
        cd rmf_schedule_visualizer
        wget https://raw.githubusercontent.com/osrf/rmf_core/master/rmf_utils/test/format/rmf_code_style.cfg
        ls
        ament_uncrustify -c rmf_code_style.cfg rviz2_plugin/ rmf_schedule_visualizer/src/ rmf_schedule_visualizer/test/
        pycodestyle .
