name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
      
    steps:
    - name: deps
      run: |
        sudo apt update
        # rmf_traffic dependencies
        sudo apt-get install libeigen3-dev libccd-dev libfcl-dev -y
        
        # mkdir -p /home/deps
        # cd /home/deps
        # git clone https://github.com/danfis/libccd
        # mkdir /home/deps/libccd/build && cd /home/deps/libccd/build
        # cmake -G "Unix Makefiles" ..
        # make && sudo make install
        
        # cd /home/deps
        # git clone https://github.com/flexible-collision-library/fcl
        # mkdir /home/deps/fcl/build && cd /home/deps/fcl/build
        # cmake ..
        # make -j4 && sudo make install
        
    - name: setup
      run: |
        cd /home/
        mkdir -p ws_rmf/src
        cd ws_rmf/src
        git clone https://github.com/osrf/traffic_editor
        git clone https://github.com/osrf/rmf_core
        git clone https://github.com/osrf/rmf_schedule_visualizer        
    - name: build
      shell: bash
      run: |
        cd /home/ws_rmf
        source /opt/ros/eloquent/setup.bash
        colcon build --packages-up-to rmf_schedule_visualizer fleet_state_visualizer rviz2_plugin
