name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
      
    steps:
    - name: deps
      run: |
        sudo apt update
        sudo apt-get install python3-shapely python3-yaml python3-requests \
        libboost-system-dev libboost-date-time-dev libboost-regex-dev libboost-random-dev -y
    - name: setup
      run: |
        cd /home/
        mkdir -p ws_rmf/src
        cd ws_rmf/src
        git clone https://github.com/osrf/traffic_editor
        git clone https://github.com/osrf/rmf_core
        git clone https://github.com/"${GITHUB_REPOSITORY}"
        
    - name: checkout
      shell: bash
      run:  |
        cd /home/ws_rmf/src/rmf_schedule_visualizer
        git checkout "${GITHUB_REF:11}"
    - name: ros-deps
      run: |
        cd /home/ws_rmf
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro eloquent -y --skip-keys "ament_python"
    - name: build
      shell: bash
      run: |
        cd /home/ws_rmf
        source /opt/ros/eloquent/setup.bash
        colcon build
